/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as CheckoutConfirmadoRouteImport } from './routes/checkout.confirmado'

const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutConfirmadoRoute = CheckoutConfirmadoRouteImport.update({
  id: '/checkout/confirmado',
  path: '/checkout/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout/confirmado': typeof CheckoutConfirmadoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout/confirmado': typeof CheckoutConfirmadoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/produtos': typeof ProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout/confirmado': typeof CheckoutConfirmadoRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout/confirmado'
    | '/produtos/$slug'
    | '/checkout/'
    | '/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout/confirmado'
    | '/produtos/$slug'
    | '/checkout'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout/confirmado'
    | '/produtos/$slug'
    | '/checkout/'
    | '/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutConfirmadoRoute: typeof CheckoutConfirmadoRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/confirmado': {
      id: '/checkout/confirmado'
      path: '/checkout/confirmado'
      fullPath: '/checkout/confirmado'
      preLoaderRoute: typeof CheckoutConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutConfirmadoRoute: CheckoutConfirmadoRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
